server:
  port: 8369
  servlet:
    context-path: /caesar


spring:
  application:
    name: caesar
  datasource:
    url: jdbc:mysql://localhost:3306/caesar?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql


schedule:
  category: dolphin
  system: dolphinscheduler
  project: caesar___caesar
  base-url: http://10.165.131.95:12345/dolphinscheduler
  version: 3.2.0
  token: 86c184558e3e773655504a39e01a1eb6
  level: workflow


engine:
  priority: shell
  environment:
    scheduler-cluster: 127.0.0.1,localhost
    hive:
      home: /opt/hive
    spark:
      home: /opt/spark
    doris:
      username: root
      password: mysql
      hostname: 127.0.0.1
      port: 3306
    mysql:
      username: root
      password: mysql
      hostname: 127.0.0.1
      port: 3306
  text:
    file-system: file
    code-dir: /Users/chavinking/test/caesar
