server:
  port: 8369
  servlet:
    context-path: /caesar


spring:
  application:
    name: caesar
  datasource:
    url: jdbc:mysql://localhost:3306/caesar?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql



## 调度模块配置信息
schedule:
  category: dolphin
  system: dolphinscheduler
  base-url: http://127.0.0.1:12345/dolphinscheduler
  version: 3.2.0
  token: b8f1c0059e65d24d9175799caa3da893
  level: workflow
  ## 调度同步方式: created - 表示创建调度时即完成同步动作; interval - 表示间隔多久自动同步; close - 关闭自动同步操作,这种条件下只能手动同步配置信息
  sync-mode: created
  projects: ## 格式 ${project}___${workflow}
    hour: caesar___caesar_hour
    day: caesar___caesar_day
    week: caesar___caesar_week
    month: caesar___caesar_month



## 执行引擎配置信息
engine:
  max-parallel-number: 16

  text:
    file-system: file
    code-dir: /Users/chavinking/test/caesar

  environment:
    ## 调度集群
    scheduler-cluster: 127.0.0.1,localhost

    ## Hive依赖
    hive:
      home: /opt/hive

    ## Spark依赖
    spark:
      home: /opt/spark

    ## Doris数据源信息
    doris:
      username: root
      password: mysql
      hostname: 127.0.0.1
      port: 3306

      username-test: root
      password-test: mysql
      hostname-test: 127.0.0.1
      port-test: 3306

    ## MySQL数据源信息
    mysql:
      style: shell ## JDBC SHELL
      username: root
      password: mysql
      hostname: 127.0.0.1
      port: 3306

      username-test: root
      password-test: mysql
      hostname-test: 127.0.0.1
      port-test: 3306


